// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmirxzktvpoxzwfapugz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaXJ4emt0dnBveHp3ZmFwdWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjA2NzAsImV4cCI6MjA2OTg5NjY3MH0.Bxi5vhxXVOoQ23oe4bcK95ZGNLG4ODHlB1qWQ3Syd5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});